Fixed a bug in Feed Export doc
scrapy/scrapy pull request #5354
Opened 2021-12-23 22:51 UTC by salehdeh76

The source code does not use return value of uri_params function and the params should be updated in place.
The document was misleading about this.

2021-12-24 08:01 UTC, wRAR approved these changes

2021-12-24 08:02 UTC, wRAR requested changes
Please make this PR merge into master instead of 2.5.

2021-12-24 10:28 UTC, wRAR commented
This merges 2.5 into master. You need to rebase your changes on top of master instead.

2021-12-24 12:03 UTC, salehdeh76 commented
> This merges 2.5 into master. You need to rebase your changes on top of master instead.

I'm Sorry. It fixed now.

2021-12-24 12:08 UTC, wRAR approved these changes

2021-12-24 12:08 UTC, wRAR commented
Thank you.

2022-01-26 12:01 UTC, elacuesta commented
Closing, this is being treated as a bug: #4962. We want to update the behavior rather than the docs.

2022-01-26 12:01 UTC, closed without merging