add typing
scrapy/scrapy pull request #6123
Opened 2023-10-30 02:17 UTC by Assistest

Python supports typing, but Scrapy does not
I don't know if my actions are correct, I haven't submitted a PR
Scrapy is the first time
Please explain any errors. Thank you

![image](https://github.com/scrapy/scrapy/assets/76395443/ede5e339-d24a-470d-83fe-c3b55549824d)
![image](https://github.com/scrapy/scrapy/assets/76395443/2c5f5d12-4923-4a31-a597-060011de2069)
![image](https://github.com/scrapy/scrapy/assets/76395443/d298ab9a-5497-472f-966a-a88443fb2d2d)
![image](https://github.com/scrapy/scrapy/assets/76395443/7ed12f56-78ae-4419-8221-c78b40a2db83)
![image](https://github.com/scrapy/scrapy/assets/76395443/8a7903dd-824c-4e6e-aa03-b7710081a3ce)
![image](https://github.com/scrapy/scrapy/assets/76395443/5eda1ca8-ad61-4f95-b053-106728bbcb33)

2023-10-30 08:20 UTC, wRAR commented
> Python supports typing, but Scrapy does not

Scrapy definitely supports typing and already ships many type hints, it's just not fully covered by them yet.

I haven't reviewed your changes yet, but I see that the typing check fails, so you should review and fix the reported issues, running it locally.

2023-10-30 08:25 UTC, wRAR requested changes

2023-10-30 08:25 UTC, wRAR commented on scrapy/http/response/__init__.py
> +        self.request: Request = request
This is incorrect, `request` can be None.

2023-10-30 08:25 UTC, wRAR commented on scrapy/pipelines/media.py
> +    def process_item(self, item: dict, spider: Spider):
`item` is not necessarily a dict.

2023-10-30 08:25 UTC, wRAR commented on scrapy/pipelines/media.py
> +    def media_to_download(self, request: Request, info: SpiderInfo, *, item: dict=None):
`item` is not necessarily a dict but in this case it can also be None.

2023-10-30 08:25 UTC, wRAR commented on scrapy/pipelines/media.py
> +    def media_downloaded(self, response: HtmlResponse, request: Request, info: SpiderInfo, *, item: dict=None):
`response` is not necessarily a `HtmlResponse`.

2023-10-30 08:25 UTC, wRAR commented on scrapy/pipelines/media.py
> +    def item_completed(self, results: List[Tuple], item: dict, info: SpiderInfo):
You should specify the tuple members types here.

2023-10-30 08:25 UTC, wRAR commented on scrapy/pipelines/media.py
> +    def file_path(self, request: Request, response: HtmlResponse=None, info: SpiderInfo=None, *, item: dict=None):
You should read about `Optional`.

2023-10-30 08:25 UTC, wRAR commented on scrapy/templates/project/module/middlewares.py.tmpl
> +    def process_start_requests(self, start_requests: Generator[Request], spider: Spider):
`start_requests` is not necessarily a `Generator[Request]`.

2023-10-30 08:25 UTC, wRAR commented on scrapy/templates/project/module/pipelines.py.tmpl
> +    def process_item(self, item: ${ProjectName}Item, spider: Spider):
item is not necessarily a `${ProjectName}Item`

2023-10-31 01:25 UTC, Assistest commented
I'm sorry I didn't understand enough  @wRAR

2023-10-31 01:25 UTC, closed without merging